### PR TITLE
[FEATURE] Add a doodle plugin

### PR DESCRIPTION
**Pull request by NamelessCoder**

### CODE REVIEW

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by xf-** [comment]
looks pretty nice.

Some of the style stuff looks like overhead:
http://getbootstrap.com/css/#forms-control-validation
Also .hide and .show

**Comment by NamelessCoder** [comment]
Rebased but not adjusted - unless you really object, please merge. EXT:builder is still beta so it's okay we're not perfect ;)

**Pull request merged**
