### PR TITLE
[TASK] Moved generation of registerProverExtensionKey to ext_localcon…

### PR DESCRIPTION
**Pull request by a-winter**
…f.php

### CODE REVIEW

**Comment by a-winter** [comment]
Fixes #96

**Comment by NamelessCoder** [comment]
If we have "Resources/Private/CodeTemplates/Extension/ext_tables.phpt" still, please remove that - I think it's no longer required.

**Comment by a-winter** [comment]
It's still required to write the configuration e. g. 
TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript', 'My provider extension');
Or should this be moved to ext_localconf.php, too?

**Comment by NamelessCoder** [comment]
> Or should this be moved to ext_localconf.php, too?

If it works with everything in localconf.php then yes please - this seems to be the preferred ext_* file for this purpose.

**Comment by a-winter** [comment]
Remove ext_tables.phpt and moved all to ext_localconf.php

**Comment by jmverges** [comment]
Sorry guys, I merge this but is not okey. As @neufeind says in #96 addStaticFile needed to be in ext_tables.php

**Pull request merged**
