### PR TITLE
[FEATURE] Adds Fluidcontent_core support by default

### PR DESCRIPTION
**Pull request by jmverges**
Related with: 
https://github.com/FluidTYPO3/fluidcontent_core/issues/176
https://github.com/FluidTYPO3/fluidcontent_core/issues/174  <-- see @konstantin83 comments
https://github.com/FluidTYPO3/fluidcontent_core/issues/177

### CODE REVIEW

**Comment by xf-** [comment]
i don't understand hasVhs - vhs is default dependency for a builder build extension

**Comment by jmverges** [comment]
It is not, you have a checkbox for it. If it is always included in the builde extension we can remove it. In my option should be always included.

**Comment by xf-** [comment]
OK, maybe let it stay and also add fluidcontent_core as option.
fluidcontent_core has a much higher impact as VHS or fluidcontent.
If you install fluidcontent_core you need to ensure AddionalConfiguration is fine, remove csc.

**Comment by jmverges** [comment]
My original idea wasn't add it as dependecy but could be okey. I thought that if user decides at some point install fluidcontent_core his fluidcontent created with builder should be fully compatible. I will add the fluidcontent_core dependecy option in other PR. 
For example, lets say I have myproviderextension and I can use it in a project with css_styled_content and it other with fluidcontent_core. "I don't want" myprovider extension has fluidcontent_core dependency but I will expect Headlines rendered in both contexts.
Makes it sense?

**Comment by NamelessCoder** [comment]
Juan is right about this one - we can add the *support* for rendering in fluidcontent_core. And we can make a switch that adds fluidcontent_core as dependency, so the developer can enable that if he knows in advance he will be using fluidcontent_core. The default state of this toggle can be ON if fluidcontent_core is installed in the system.

**Pull request merged**
